{
    "className": "OrbitNPanControlScript",
    "name": "ToolCameraScript",
    "options": {
        "baseDistance": 5,
        "drag": 5,
        "interpolationSpeed": 100,
        "lookAtPoint": [
            0,
            0,
            0
        ],
        "maxZoomDistance": 6000,
        "minZoomDistance": 0.1,
        "releaseVelocity": false,
        "spherical": [
            8.412643432617188,
            1.9265938997268677,
            0.4899996519088745
        ],
        "zoomSpeed": 0.3
    },
    "ref": "scripts/ToolCameraScript.script"
}